name: 'Terragrunt GitHub Actions'
description: 'Wraps Terragrunt commands on HashiCorps GitHub Actions.'
author: 'HashiCorp, Inc. Terraform Team <terraform@hashicorp.com> with custom Terragrunt modifications.'
branding:
  icon: 'terminal'
  color: 'purple'
inputs:
  tf_actions_version:
    description: 'Terraform version to install.'
    required: true
  tg_actions_version:
    description: 'Terragrunt version to install.'
    required: true
  tf_actions_subcommand:
    description: 'Terragrunt subcommand to execute.'
    required: true
  tf_actions_working_dir:
    description: 'Terragrunt working directory.'
    default: '.'
  tf_actions_comment:
    description: 'Whether or not to comment on pull requests.'
    default: true
outputs:
  tf_actions_plan_has_changes:
    description: 'Whether or not the Terraform plan contained changes.'
  tf_actions_output:
    description: 'The Terraform outputs in JSON format.'
runs:
  using: 'docker'
  image: './Dockerfile'
